sudo: false
language: elixir
elixir:
  - 1.8
  - 1.9
otp_release:
  - 21.0
  - 22.0
before_script:
  - epmd -daemon
  - MIX_ENV=test mix deps.get
script:
  - "BOOT_TIMEOUT=30000 MIX_ENV=test mix test"
notifications:
  recipients:
    - paulschoenfelder@fastmail.com
